sudo: false
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
services:
  - redis-server
node_js:
  - 'stable'
before_install:
- npm install -g yarn
install:
- yarn
- npm rebuild node-sass
script:
- npm run lint
- make build
- npm run test:coverage
after_success:
#  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
