export const CheckingAccountCreatedEvent = 'CheckingAccountCreatedEvent'
export const CheckingAccountPropertyChangedEvent = 'CheckingAccountPropertyChangedEvent'
export const CheckingAccountUserCreatedEvent = 'CheckingAccountUserCreatedEvent'
export const PeriodicalCreatedEvent = 'PeriodicalCreatedEvent'
export const SpendingCreatedEvent = 'SpendingCreatedEvent'
export const SpendingDeletedEvent = 'SpendingDeletedEvent'
export const SpendingUpdatedEvent = 'SpendingUpdatedEvent'
